# Changes here will be overwritten by Copier
_commit: v0.3.5
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage vault
distribution_name: swh-vault
have_cli: true
have_workers: true
package_root: swh/vault
project_name: swh.vault
python_minimal_version: '3.10'
readme_format: rst
